---
apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: platform-ingress
  namespace: platform-config
spec:
  listeners:
  - http: {}
    port:
      number: 80
  workloads:
  - selector:
      cluster: mgmt-cluster
      labels:
        istio: ingressgateway
---
apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: platform-ingress
  namespace: platform-config
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: platform-ingress
      namespace: platform-config
      cluster: mgmt-cluster
  http:
    - name: sanity
      matchers:
        - uri:
            prefix: /sanity
      labels:
        route: sanity
      directResponse:
        status: 200
        body: "it's alive"
