---
apiVersion: v1
kind: Namespace
metadata:
  name: workspace-config
---
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: workspace
  namespace: gloo-mesh
  labels:
    gloo.solo.io/team: 'default'
spec:
  workloadClusters:
  - name: 'mgmt-cluster'
    namespaces:
    - name: workspace-config
    - name: gloo-mesh
    - name: gloo-mesh-gateways
    - name: gloo-mesh-addons
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: workspace
  namespace: workspace-config
spec:
  options:
    federation:                
      enabled: false
    eastWestGateways:      
    - selector:
        labels:
          istio: eastwestgateway
    serviceIsolation:     
      enabled: true
      trimProxyConfig: true