
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ben-default-aws-lb
  namespace: argocd
  labels:
    solo.io/infra: aws-load-balancer
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    targetRevision: "1.4.5"
    chart: aws-load-balancer-controller
    helm:
      values: |
        replicaCount: 1
        clusterName: ben-default
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::931713665590:role/ben-default-aws-lb-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system  
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ben-default-ext-secrets
  namespace: argocd
  labels:
    solo.io/infra: external-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: "0.7.2"
    chart: external-secrets
    helm:
      values: |
        serviceAccount:
          create: true
          name: external-secrets
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::931713665590:role/ben-default-ext-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system  
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ben-default-cert-manager
  namespace: argocd
  labels:
    solo.io/infra: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.9.1
    chart: cert-manager
    helm:
      values: |
        installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system  
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ben-default-external-dns
  namespace: argocd
  labels:
    solo.io/infra: external-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/external-dns
    targetRevision: v0.13.5
    path: charts/external-dns
    helm:
      values: |
        serviceAccount:
          name: external-dns
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::931713665590:role/ben-default-ext-dns
        sources:
        - service
        provider: aws
        registry: txt
        txtPrefix: ben-default
        txtOwnerId: external-dns-ben-default
        domainFilters:
        - ben.vpc
        extraArgs: 
        - --aws-zone-type=private
        env:
        - name: AWS_DEFAULT_REGION
          value: us-east-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
