---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws
  namespace: gloo-mesh
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gloo-platform-license
  namespace: gloo-mesh
spec:
  secretStoreRef:
    name: aws
    kind: SecretStore
  target:
    name: gloo-platform-license
  dataFrom:
  - extract:
      key: gloo-platform-license