---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mgmt-server
  namespace: gloo-mesh
spec:
  # Secret names are always required.
  secretName: mgmt-server-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - gloo-mesh-mgmt-server
  commonName: gloo-mesh-mgmt-server
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "*.gloo-mesh"
    - "*.vpc"
    - "*.example.com"
    - "*.elb.us-east-1.amazonaws.com"
    - "*.elb.us-west-1.amazonaws.com"
  # Issuer references are always required.
  issuerRef:
    name: root-ca
    kind: Issuer